// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKyKxJZQIKYqQA52GnkDqdody-ZpfseM',
    appId: '1:92903673939:web:9aa1c65fcfae19d1dbb6a6',
    messagingSenderId: '92903673939',
    projectId: 'trial-apghar',
    authDomain: 'trial-apghar.firebaseapp.com',
    storageBucket: 'trial-apghar.appspot.com',
    measurementId: 'G-82XXCXYKD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeqX808-XYmfPhxGQ6Dns8tSRuZnJjcI',
    appId: '1:92903673939:android:c1d68085a6f505efdbb6a6',
    messagingSenderId: '92903673939',
    projectId: 'trial-apghar',
    storageBucket: 'trial-apghar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbL2VFQEP4DraIJ1A5WQ4JSRm8L1GL7FM',
    appId: '1:92903673939:ios:b84978f80ae8cab8dbb6a6',
    messagingSenderId: '92903673939',
    projectId: 'trial-apghar',
    storageBucket: 'trial-apghar.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbL2VFQEP4DraIJ1A5WQ4JSRm8L1GL7FM',
    appId: '1:92903673939:ios:b84978f80ae8cab8dbb6a6',
    messagingSenderId: '92903673939',
    projectId: 'trial-apghar',
    storageBucket: 'trial-apghar.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKyKxJZQIKYqQA52GnkDqdody-ZpfseM',
    appId: '1:92903673939:web:0675e66866a13865dbb6a6',
    messagingSenderId: '92903673939',
    projectId: 'trial-apghar',
    authDomain: 'trial-apghar.firebaseapp.com',
    storageBucket: 'trial-apghar.appspot.com',
    measurementId: 'G-1P6KP11DVK',
  );
}
